Repository DeveloperAcademy-POSTECH/MacC-Team7-FallWin, pull requests merged in 2023-10, with the labels that each got.

#2 [Feat] CvasTabView 작업
  FallWin/Assets.xcassets/backgroundOnTabBar.colorset/Contents.json
  FallWin/Assets.xcassets/backgroundPrimary.colorset/Contents.json
  FallWin/Assets.xcassets/backgroundSecondary.colorset/Contents.json
  FallWin/Assets.xcassets/backgroundTabBar.colorset/Contents.json
  FallWin/Assets.xcassets/backgroundTertiary.colorset/Contents.json
  FallWin/Component/Colors.swift
  FallWin/Component/CvasTabView.swift
  FallWin/Component/TabBarLabelStyle.swift
Labels: Feature

#4 [Feat] TabView에 포함되는 네 개의 View (Gallery, Search, Surf, Profile) 및 Feature 개발 [#3]
  FallWin.xcodeproj/project.pbxproj
  FallWin/FallWinApp.swift
  FallWin/View/ContentView.swift
  FallWin/View/Feature.swift
  FallWin/View/Gallery/GalleryView+Feature.swift
  FallWin/View/Gallery/GalleryView.swift
  FallWin/View/Profile/ProfileView+Feature.swift
  FallWin/View/Profile/ProfileView.swift
  FallWin/View/Search/SearchView+Feature.swift
  FallWin/View/Search/SearchView.swift
  FallWin/View/Surf/SurfView+Feature.swift
  FallWin/View/Surf/SurfView.swift
Labels: Feature

#17 Test/merge
  FallWin.xcodeproj/project.pbxproj
  FallWin/Component/WritingPathState.swift
  FallWin/FallWinApp.swift
  FallWin/View/ContentView.swift
  FallWin/View/Gallery/GalleryView+Feature.swift
  FallWin/View/Gallery/GalleryView.swift
  FallWin/View/Writing/DrawingStyleView+Feature.swift
  FallWin/View/Writing/DrawingStyleView.swift
  FallWin/View/Writing/GeneratedDiaryView+Feature.swift
  FallWin/View/Writing/GeneratedDiaryView.swift
  FallWin/View/Writing/MainTextView+Feature.swift
  FallWin/View/Writing/MainTextView.swift
  FallWin/View/Writing/WritingView+Feature.swift
  FallWin/View/Writing/WritingView.swift
Labels: Fix, Feature, Refactor

#19 [Style] 디자인 수정[#6]
  FallWin.xcodeproj/project.pbxproj
  FallWin/Extension/Color+Extension.swift
  FallWin/Extension/UIColor+Extension.swift
  FallWin/View/Writing/DrawingStyleView.swift
  FallWin/View/Writing/WritingView.swift
Labels: Style
